# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            APIs for cats
tagline:          'and cat lovers'
description:      'APIs for cats'
url:              http://rforcats.net/

author:
  name:           'Scott Chamberlain'
  url:            https://twitter.com/sckottie

github:
  repo:           https://github.com/sckott/apisforcats
